//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ConnectionString : DbContext
    {
        public ConnectionString()
            : base("name=ConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Ledger> Ledgers { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<OrderMaster> OrderMasters { get; set; }
        public DbSet<PaymentDetail> PaymentDetails { get; set; }
        public DbSet<PaymentMode> PaymentModes { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductMaster> ProductMasters { get; set; }
        public DbSet<Purchaser> Purchasers { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
    
        public virtual ObjectResult<Generate_POInvoice_Result> Generate_POInvoice(string orderNo)
        {
            var orderNoParameter = orderNo != null ?
                new ObjectParameter("OrderNo", orderNo) :
                new ObjectParameter("OrderNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Generate_POInvoice_Result>("Generate_POInvoice", orderNoParameter);
        }
    
        public virtual ObjectResult<GenerateOrderNumber_Result> GenerateOrderNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GenerateOrderNumber_Result>("GenerateOrderNumber");
        }
    
        public virtual int GetAllPayments(string purchaser)
        {
            var purchaserParameter = purchaser != null ?
                new ObjectParameter("Purchaser", purchaser) :
                new ObjectParameter("Purchaser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllPayments", purchaserParameter);
        }
    
        public virtual int GetAllPO(string purchaser)
        {
            var purchaserParameter = purchaser != null ?
                new ObjectParameter("Purchaser", purchaser) :
                new ObjectParameter("Purchaser", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetAllPO", purchaserParameter);
        }
    
        public virtual ObjectResult<GetAllPurchaser_Result> GetAllPurchaser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPurchaser_Result>("GetAllPurchaser");
        }
    
        public virtual ObjectResult<GetAllPurchaser1_Result> GetAllPurchaser1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPurchaser1_Result>("GetAllPurchaser1");
        }
    
        public virtual ObjectResult<GetLedger_Result> GetLedger()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLedger_Result>("GetLedger");
        }
    
        public virtual int GetLedgerBalance(string purChaserID)
        {
            var purChaserIDParameter = purChaserID != null ?
                new ObjectParameter("PurChaserID", purChaserID) :
                new ObjectParameter("PurChaserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLedgerBalance", purChaserIDParameter);
        }
    
        public virtual int GetLedgerBalance2(string purChaserID)
        {
            var purChaserIDParameter = purChaserID != null ?
                new ObjectParameter("PurChaserID", purChaserID) :
                new ObjectParameter("PurChaserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLedgerBalance2", purChaserIDParameter);
        }
    
        public virtual ObjectResult<Usp_GenerateOrderNumber_Result> Usp_GenerateOrderNumber()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GenerateOrderNumber_Result>("Usp_GenerateOrderNumber");
        }
    
        public virtual int PaymentStatementByDate(string purchaser, string startDate, string endDate)
        {
            var purchaserParameter = purchaser != null ?
                new ObjectParameter("Purchaser", purchaser) :
                new ObjectParameter("Purchaser", typeof(string));
    
            var startDateParameter = startDate != null ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(string));
    
            var endDateParameter = endDate != null ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaymentStatementByDate", purchaserParameter, startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<Usp_GetYearwisepaymentdetails_Result> Usp_GetYearwisepaymentdetails(Nullable<long> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usp_GetYearwisepaymentdetails_Result>("Usp_GetYearwisepaymentdetails", yearParameter);
        }
    
        public virtual ObjectResult<Generate_PaymentReceipt_Result> Generate_PaymentReceipt(string paymentID)
        {
            var paymentIDParameter = paymentID != null ?
                new ObjectParameter("PaymentID", paymentID) :
                new ObjectParameter("PaymentID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Generate_PaymentReceipt_Result>("Generate_PaymentReceipt", paymentIDParameter);
        }
    
        public virtual int GetLedgerBalanceByID(string purChaserID)
        {
            var purChaserIDParameter = purChaserID != null ?
                new ObjectParameter("PurChaserID", purChaserID) :
                new ObjectParameter("PurChaserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLedgerBalanceByID", purChaserIDParameter);
        }
    
        public virtual ObjectResult<UspDashBoard_Result> UspDashBoard()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UspDashBoard_Result>("UspDashBoard");
        }
    
        public virtual int UspShowInventory(string fromDate, string toDate)
        {
            var fromDateParameter = fromDate != null ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UspShowInventory", fromDateParameter, toDateParameter);
        }
    }
}
