//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public long LedgerID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public System.DateTime TransDate { get; set; }
        public Nullable<long> PurchaserID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<long> PaymentDetailID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual OrderMaster OrderMaster { get; set; }
        public virtual PaymentDetail PaymentDetail { get; set; }
        public virtual Purchaser Purchaser { get; set; }
    }
}
