//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public PaymentDetail()
        {
            this.Ledgers = new HashSet<Ledger>();
        }
    
        public long PaymentID { get; set; }
        public Nullable<long> PurchaserID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public int PaymentModeID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal PaymentAmount { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Ledger> Ledgers { get; set; }
        public virtual User User { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
        public virtual Purchaser Purchaser { get; set; }
    }
}
