//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corporate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int Quantity { get; set; }
        public string ItemDescription { get; set; }
    
        public virtual OrderMaster OrderMaster { get; set; }
    }
}
